name: flutter_common
description: Flutter工程基础组件通用库.
version: 0.0.1
author: niujinyong
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## 开源库
  dio: 2.1.13                   # 网络库
  fluro: ^1.5.1                 # 路由框架
  common_utils: ^1.1.3          # Dart 常用工具类库
  flustars: ^0.2.6+1            # 常用工具类库
  sprintf: ^4.0.2               # 格式化String
  shared_preferences: ^0.5.3+4  # 持久化存储简单数据
  path_provider: ^1.2.2         # 原生文件路径
  device_info: ^0.4.1+1         # 设备信息
  flutter_bloc: ^2.0.0

#  toon_plugin:
#    git:
#      url: http://172.28.39.87/flutter/flutter-plugin.git
#      ref: develop
#      path: toon_plugin/
#    path: ../../flutter-plugin/toon_plugin/

  flutter_plugin:
    git:
      url: http://172.28.39.87/flutter/flutter-plugin.git
      ref: develop
      path: flutter_plugin/
#      path: ../../flutter-plugin/flutter_plugin/

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
